Upgrade to Nuke 6.1.2
OctopusDeploy/Time pull request #28
Opened 2022-07-13 06:38 UTC by michaelongso

2022-07-13 22:38 UTC, skermajo requested changes
Just a minor nitpick about the logging, once that's sorted it's looking good.

2022-07-13 22:38 UTC, skermajo commented on build/Build.cs
> +            Log.Information("Building Octopus.Time v{0}", OctoVersionInfo.FullSemVer);
Nitpick about these logging conversions. With the structured logging of Serilog we can use named parameter values now instead of indexes (example below). More info is available in our [logging docs](https://github.com/OctopusDeploy/OctopusDeploy/blob/master/docs/OBSERVABILITY/Logging.md).

```csharp
Log.Information("Building Ovtopus.Time v{Version}", OctoVersionInfo.FullSemVer);
```

2022-07-13 22:54 UTC, michaelongso commented on build/Build.cs
> +            Log.Information("Building Octopus.Time v{0}", OctoVersionInfo.FullSemVer);
Thanks for pointing this out!

2022-07-14 00:27 UTC, skermajo approved these changes
Thanks, LGTM 👍

2022-07-14 00:28 UTC, merged